export const AdminTypes = {
  UPDATE_EVENT_REQUEST: 'UPDATE_EVENT_REQUEST',
  UPDATE_EVENT_REQUEST_SUCCESS: 'UPDATE_EVENT_REQUEST_SUCCESS',
  UPDATE_EVENT_REQUEST_FAIL: 'UPDATE_EVENT_REQUEST_FAIL',

  CREATE_EVENT_REQUEST: 'CREATE_EVENT_REQUEST',
  CREATE_EVENT_REQUEST_SUCCESS: 'CREATE_EVENT_REQUEST_SUCCESS',
  CREATE_EVENT_REQUEST_FAIL: 'CREATE_EVENT_REQUEST_FAIL',

  GET_LOGGED_ADMIN_REQUEST: 'GET_LOGGED_ADMIN_REQUEST',
  GET_LOGGED_ADMIN_REQUEST_SUCCESS: 'GET_LOGGED_ADMIN_REQUEST_SUCCESS',
  GET_LOGGED_ADMIN_REQUEST_FAIL: 'GET_LOGGED_ADMIN_REQUEST_FAIL',

  GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
  GET_COMPANIES_REQUEST_SUCCESS: 'GET_COMPANIES_REQUEST_SUCCESS',
  GET_COMPANIES_REQUEST_FAIL: 'GET_COMPANIES_REQUEST_FAIL',

  ARCHIVE_COMPANY_REQUEST: 'ARCHIVE_COMPANY_REQUEST',
  ARCHIVE_COMPANY_REQUEST_SUCCESS: 'ARCHIVE_COMPANY_REQUEST_SUCCESS',
  ARCHIVE_COMPANY_REQUEST_FAIL: 'ARCHIVE_COMPANY_REQUEST_FAIL',

  DELETE_COMPANY_REQUEST: 'DELETE_COMPANY_REQUEST',
  DELETE_COMPANY_REQUEST_SUCCESS: 'DELETE_COMPANY_REQUEST_SUCCESS',
  DELETE_COMPANY_REQUEST_FAIL: 'DELETE_COMPANY_REQUEST_FAIL',

  GET_ARCHIVED_COMPANIES_REQUEST: 'GET_ARCHIVE_COMPANY_REQUEST',
  GET_ARCHIVED_COMPANIES_REQUEST_SUCCESS: 'GET_ARCHIVE_COMPANY_REQUEST_SUCCESS',
  GET_ARCHIVED_COMPANIES_REQUEST_FAIL: 'GET_ARCHIVE_COMPANY_REQUEST_FAIL',

  GET_CANDIDATES_REQUEST: 'GET_CANDIDATES_REQUEST',
  GET_CANDIDATES_REQUEST_SUCCESS: 'GET_CANDIDATES_REQUEST_SUCCESS',
  GET_CANDIDATES_REQUEST_FAIL: 'GET_CANDIDATES_REQUEST_FAIL',

  GET_ARCHIVED_CANDIDATES_REQUEST: 'GET_ARCHIVED_CANDIDATES_REQUEST',
  GET_ARCHIVED_CANDIDATES_REQUEST_SUCCESS: 'GET_ARCHIVED_CANDIDATES_REQUEST_SUCCESS',
  GET_ARCHIVED_CANDIDATES_REQUEST_FAIL: 'GET_ARCHIVED_CANDIDATES_REQUEST_FAIL',

  ARCHIVE_CANDIDATE_REQUEST: 'ARCHIVE_CANDIDATE_REQUEST',
  ARCHIVE_CANDIDATE_REQUEST_SUCCESS: 'ARCHIVE_CANDIDATE_REQUEST_SUCCESS',
  ARCHIVE_CANDIDATE_REQUEST_FAIL: 'ARCHIVE_CANDIDATE_REQUEST_FAIL',

  REVERT_CANDIDATE_REQUEST: 'REVERT_CANDIDATE_REQUEST',
  REVERT_CANDIDATE_REQUEST_SUCCESS: 'REVERT_CANDIDATE_REQUEST_SUCCESS',
  REVERT_CANDIDATE_REQUEST_FAIL: 'REVERT_CANDIDATE_REQUEST_FAIL',

  DELETE_CANDIDATE_REQUEST: 'DELETE_CANDIDATE_REQUEST',
  DELETE_CANDIDATE_REQUEST_SUCCESS: 'DELETE_CANDIDATE_REQUEST_SUCCESS',
  DELETE_CANDIDATE_REQUEST_FAIL: 'DELETE_CANDIDATE_REQUEST_FAIL',

  GET_ACTIVITIES_REQUEST: 'GET_ACTIVITIES_REQUEST',
  GET_ACTIVITIES_REQUEST_SUCCESS: 'GET_ACTIVITIES_REQUEST_SUCCESS',
  GET_ACTIVITIES_REQUEST_FAIL: 'GET_ACTIVITIES_REQUEST_FAIL',

  GET_ONLY_COMPANIES_REQUEST: 'GET_ONLY_COMPANIES_REQUEST',
  GET_ONLY_COMPANIES_REQUEST_SUCCESS: 'GET_ONLY_COMPANIES_REQUEST_SUCCESS',
  GET_ONLY_COMPANIES_REQUEST_FAIL: 'GET_ONLY_COMPANIES_REQUEST_FAIL',

  GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
  GET_EVENTS_REQUEST_SUCCESS: 'GET_EVENTS_REQUEST_SUCCESS',
  GET_EVENTS_REQUEST_FAIL: 'GET_EVENTS_REQUEST_FAIL',

  GET_EVENT_REQUEST: 'GET_EVENT_REQUEST',
  GET_EVENT_REQUEST_SUCCESS: 'GET_EVENT_REQUEST_SUCCESS',
  GET_EVENT_REQUEST_FAIL: 'GET_EVENT_REQUEST_FAIL',

}