export const authTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',

  LOGIN_ADMIN_REQUEST: 'LOGIN_ADMIN_REQUEST',
  LOGIN_ADMIN_REQUEST_SUCCESS: 'LOGIN_ADMIN_REQUEST_SUCCESS',
  LOGIN_ADMIN_REQUEST_FAIL: 'LOGIN_ADMIN_REQUEST_FAIL',

  REGISTER_CANDIDATE_REQUEST: 'REGISTER_CANDIDATE_REQUEST',
  REGISTER_CANDIDATE_REQUEST_SUCCESS: 'REGISTER_CANDIDATE_REQUEST_SUCCESS',
  REGISTER_CANDIDATE_REQUEST_FAIL: 'REGISTER_CANDIDATE_REQUEST_FAIL',

  REGISTER_EMPLOYER_REQUEST: 'REGISTER_EMPLOYER_REQUEST',
  REGISTER_EMPLOYER_REQUEST_SUCCESS: 'REGISTER_EMPLOYER_REQUEST_SUCCESS',
  REGISTER_EMPLOYER_REQUEST_FAIL: 'REGISTER_EMPLOYER_REQUEST_FAIL',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST_SUCCESS: 'RESET_PASSWORD_REQUEST_SUCCESS',
  RESET_PASSWORD_REQUEST_FAIL: 'RESET_PASSWORD_REQUEST_FAIL',

  RESET_PASSWORD_EMAIL_REQUEST: 'RESET_PASSWORD_EMAIL_REQUEST',
  RESET_PASSWORD_EMAIL_REQUEST_SUCCESS: 'RESET_PASSWORD_EMAIL_REQUEST_SUCCESS',
  RESET_PASSWORD_EMAIL_REQUEST_FAIL: 'RESET_PASSWORD_EMAIL_REQUEST_FAIL',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_REQUEST_SUCCESS: 'CHANGE_PASSWORD_REQUEST_SUCCESS',
  CHANGE_PASSWORD_REQUEST_FAIL: 'CHANGE_PASSWORD_REQUEST_FAIL',

  ACTIVATION_REQUEST: 'ACTIVATION_REQUEST',
  ACTIVATION_REQUEST_SUCCESS: 'ACTIVATION_REQUEST_SUCCESS',
  ACTIVATION_REQUEST_FAIL: 'ACTIVATION_REQUEST_FAIL',

  SET_LOGIN_STATE: 'SET_LOGIN_STATE',

  LOGOUT: 'LOGOUT',

}