export const candidateTypes = {
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_REQUEST_SUCCESS: 'GET_PROFILE_REQUEST_SUCCESS',
  GET_PROFILE_REQUEST_FAIL: 'GET_PROFILE_REQUEST_FAIL',

  GET_LOGGED_USER_REQUEST: 'GET_LOGGED_USER_REQUEST',
  GET_LOGGED_USER_REQUEST_SUCCESS: 'GET_LOGGED_USER_REQUEST_SUCCESS',
  GET_LOGGED_USER_REQUEST_FAIL: 'GET_LOGGED_USER_REQUEST_FAIL',

  GET_SINGLE_EMPLOYER_REQUEST: 'GET_SINGLE_EMPLOYER_REQUEST',
  GET_SINGLE_EMPLOYER_REQUEST_SUCCESS: 'GET_SINGLE_EMPLOYER_REQUEST_SUCCESS',
  GET_SINGLE_EMPLOYER_REQUEST_FAIL: 'GET_SINGLE_EMPLOYER_REQUEST_FAIL',

  GET_INTERVIEWS_REQUEST: 'GET_INTERVIEWS_REQUEST',
  GET_INTERVIEWS_REQUEST_SUCCESS: 'GET_INTERVIEWS_REQUEST_SUCCESS',
  GET_INTERVIEWS_REQUEST_FAIL: 'GET_INTERVIEWS_REQUEST_FAIL',

  GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
  GET_COMPANIES_REQUEST_SUCCESS: 'GET_COMPANIES_REQUEST_SUCCESS',
  GET_COMPANIES_REQUEST_FAIL: 'GET_COMPANIES_REQUEST_FAIL',

  GET_TIMES_FOR_DAY_REQUEST: 'GET_TIMES_FOR_DAY_REQUEST',
  GET_TIMES_FOR_DAY_REQUEST_SUCCESS: 'GET_TIMES_FOR_DAY_REQUEST_SUCCESS',
  GET_TIMES_FOR_DAY_REQUEST_FAIL: 'GET_TIMES_FOR_DAY_REQUEST_FAIL',

  ADD_FAVORITE_REQUEST: 'ADD_FAVORITE_REQUEST',
  ADD_FAVORITE_REQUEST_SUCCESS: 'ADD_FAVORITE_REQUEST_SUCCESS',
  ADD_FAVORITE_REQUEST_FAIL: 'ADD_FAVORITE_REQUEST_FAIL',

  DELETE_FAVORITE_REQUEST: 'DELETE_FAVORITE_REQUEST',
  DELETE_FAVORITE_REQUEST_SUCCESS: 'DELETE_FAVORITE_REQUEST_SUCCESS',
  DELETE_FAVORITE_REQUEST_FAIL: 'DELETE_FAVORITE_REQUEST_FAIL',

  GET_FAVORITE_REQUEST: 'GET_FAVORITE_REQUEST',
  GET_FAVORITE_REQUEST_SUCCESS: 'GET_FAVORITE_REQUEST_SUCCESS',
  GET_FAVORITE_REQUEST_FAIL: 'GET_FAVORITE_REQUEST_FAIL',

}