export const employerTypes = {
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_REQUEST_SUCCESS: 'GET_PROFILE_REQUEST_SUCCESS',
  GET_PROFILE_REQUEST_FAIL: 'GET_PROFILE_REQUEST_FAIL',

  GET_SETTINGS_REQUEST: 'GET_SETTINGS_REQUEST',
  GET_SETTINGS_REQUEST_SUCCESS: 'GET_SETTINGS_REQUEST_SUCCESS',
  GET_SETTINGS_REQUEST_FAIL: 'GET_SETTINGS_REQUEST_FAIL',

  SETTINGS_REQUEST: 'SETTINGS_REQUEST',
  SETTINGS_REQUEST_SUCCESS: 'SETTINGS_REQUEST_SUCCESS',
  SETTINGS_REQUEST_FAIL: 'SETTINGS_REQUEST_FAIL',

  UPDATE_SETTINGS_REQUEST: 'UPDATE_SETTINGS_REQUEST',
  UPDATE_SETTINGS_REQUEST_SUCCESS: 'UPDATE_SETTINGS_REQUEST_SUCCESS',
  UPDATE_SETTINGS_REQUEST_FAIL: 'UPDATE_SETTINGS_REQUEST_FAIL',

  GET_LOGGED_USER_REQUEST: 'GET_LOGGED_USER_REQUEST',
  GET_LOGGED_USER_REQUEST_SUCCESS: 'GET_LOGGED_USER_REQUEST_SUCCESS',
  GET_LOGGED_USER_REQUEST_FAIL: 'GET_LOGGED_USER_REQUEST_FAIL',

  GET_ATTACHED_FILES_REQUEST: 'GET_ATTACHED_FILES_REQUEST',
  GET_ATTACHED_FILES_REQUEST_SUCCESS: 'GET_ATTACHED_FILES_REQUEST_SUCCESS',
  GET_ATTACHED_FILES_REQUEST_FAIL: 'GET_ATTACHED_FILES_REQUEST_FAIL',

  GET_INTERVIEWS_REQUEST: 'GET_INTERVIEWS_REQUEST',
  GET_INTERVIEWS_REQUEST_SUCCESS: 'GET_INTERVIEWS_REQUEST_SUCCESS',
  GET_INTERVIEWS_REQUEST_FAIL: 'GET_INTERVIEWS_REQUEST_FAIL',

}